// <auto-generated />
using EFDataAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDataAccessLibrary.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211102140229_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDataAccessLibrary.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "شخصیتی",
                            QuestionStr = "وقتی صحبت از دوستی می شود کدام ویژگی برای تو بیشترین ارزش را دارد؟ و اینکه آیا به راحتی دوست می شوی؟"
                        },
                        new
                        {
                            Id = 2,
                            Category = "چالش",
                            QuestionStr = "آیا تا به حال از کسی سو استفاده کرده ای؟"
                        },
                        new
                        {
                            Id = 3,
                            Category = "سرگرمی",
                            QuestionStr = " اگر یک حیوان بودی چه بودی؟"
                        },
                        new
                        {
                            Id = 4,
                            Category = "شخصیتی",
                            QuestionStr = "آیا خود را شخص قابل اعتمادی می دانید؟ آیا دوستان تان شما را قابل اعتماد می دانند؟"
                        },
                        new
                        {
                            Id = 5,
                            Category = "شخصیتی",
                            QuestionStr = "آیا خرافاتی هستی؟"
                        },
                        new
                        {
                            Id = 6,
                            Category = "شخصیتی",
                            QuestionStr = "آیا خودت را متعصب یا نژادپرست می دانید؟"
                        },
                        new
                        {
                            Id = 7,
                            Category = "چالش",
                            QuestionStr = "بدترین رازت را بگو؟"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
