// <auto-generated />
using EFDataAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDataAccessLibrary.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220103141322_RemoveGuid")]
    partial class RemoveGuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDataAccessLibrary.Models.Dare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DareStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 3,
                            CategoryName = "فیزیکی",
                            DareStr = "به مدت پنج دقیقه پاهای شرکت کننده سمت چپ خود را ماساژ بده"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            DareStr = "یک قاشق کره بخور"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 2,
                            CategoryName = "سرگرمی",
                            DareStr = "اولین کلمه ای که به ذهنت می رسد را فریاد بزن"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            DareStr = "یک قطعه یخ در شلوار خود قرار بده و صبر کن تا آب شود"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            DareStr = "ده بار دور خودت بگرد، بعد از آن سعی کن در خط مستقیم راه بروی"
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            DareStr = "با آهنگ انتخابی گروه برقص"
                        });
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 0,
                            CategoryName = "شخصیتی",
                            QuestionStr = "وقتی صحبت از دوستی می شود کدام ویژگی برای تو بیشترین ارزش را دارد؟ و اینکه آیا به راحتی دوست می شوی؟"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            QuestionStr = "آیا تا به حال از کسی سو استفاده کرده ای؟"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 2,
                            CategoryName = "سرگرمی",
                            QuestionStr = " اگر یک حیوان بودی چه بودی؟"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 0,
                            CategoryName = "شخصیتی",
                            QuestionStr = "آیا خود را شخص قابل اعتمادی می دانید؟ آیا دوستان تان شما را قابل اعتماد می دانند؟"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 0,
                            CategoryName = "شخصیتی",
                            QuestionStr = "آیا خرافاتی هستی؟"
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 0,
                            CategoryName = "شخصیتی",
                            QuestionStr = "آیا خودت را متعصب یا نژادپرست می دانید؟"
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 1,
                            CategoryName = "چالش",
                            QuestionStr = "بدترین رازت را بگو؟"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
